@startuml

actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Add a Customer
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": name, address, phone, creditcard number, creditcard date

create "creditCard :CreditCard"
":UserInterface" -> "creditCard :CreditCard" : creditCard = new CreditCard(creditcard number, creditcard date)

":UserInterface" -> ":Theater" : getCustomerList()
activate ":Theater"
":Theater" -->> ":UserInterface": customerList
deactivate ":Theater"
":UserInterface" -> ":CustomerList": id = getNewAccountId()
create "customer :Customer"
":UserInterface" -> "customer :Customer": customer = Customer(id, name, address, phone, creditCard)
":UserInterface" -> ":CustomerList" : boolean = addAccount(customer)
activate ":CustomerList"
":CustomerList" -->> ":UserInterface" : successful?
deactivate ":CustomerList"
":UserInterface" -->> Clerk : successful?
deactivate ":UserInterface"
@enduml