@startuml

actor Clerk

activate ":Interface"
Clerk -> ":Interface" : Add a Client
Clerk //- ":Interface": Data Request
Clerk -// ":Interface": name, address, phone

":Interface" -> ":Theater" : getClientList()
activate ":Theater"
":Theater" -->> ":Interface": clientList
deactivate ":Theater"
":Interface" -> ":ClientList": id = getNewAccountId()
create "client :Client"
":Interface" -> "client :Client": client = Client(id, name, address, phone)
":Interface" -> ":ClientList" : boolean = addAccount(client)
activate ":ClientList"
":ClientList" -->> ":Interface" : successful?
deactivate ":ClientList"
":Interface" -->> Clerk : successful?
deactivate ":Interface"
@enduml