@startuml

actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Add a Client
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": name, address, phone

":UserInterface" -> ":Theater" : getClientList()
activate ":Theater"
":Theater" -->> ":UserInterface": clientList
deactivate ":Theater"
":UserInterface" -> ":ClientList": id = getNewAccountId()
create "client :Client"
":UserInterface" -> "client :Client": client = Client(id, name, address, phone)
":UserInterface" -> ":ClientList" : boolean = addAccount(client)
activate ":ClientList"
":ClientList" -->> ":UserInterface" : successful?
deactivate ":ClientList"
":UserInterface" -->> Clerk : successful?
deactivate ":UserInterface"
@enduml