@startuml
actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Add a Show
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": clientId, showName, startDate, endDate

":UserInterface" -> ":Theater" : getShowList()
activate ":Theater"
":Theater" -->> ":UserInterface": showList
deactivate ":Theater"
":UserInterface" -> ":ClientList": client = getAccount(clientId)
create "show :Show"
":UserInterface" -> "show :Show": show = Show(client, showName, startDate, endDate)
":UserInterface" -> ":ShowList" : boolean = addShow(show)
activate ":ShowList"
":ShowList" -->> ":UserInterface" : successful?
deactivate ":ShowList"
":UserInterface" -->> Clerk : successful?
deactivate ":UserInterface"
@enduml