@startuml
actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Exit program

":UserInterface" -> ":Theater" : boolean = storeData()
activate ":Theater"
":Theater" -->> ":UserInterface": successful?
destroy ":Theater"
":UserInterface" -->> Clerk : successful?
destroy ":UserInterface"
@enduml