@startuml

actor Clerk

Clerk -> ":UserInterface" : Show List
activate ":UserInterface"

":UserInterface" -> ":Theater" : getShowList()
activate ":Theater"
":Theater" -->> ":UserInterface": showList
deactivate ":Theater"
":UserInterface" -> ":ShowList": showList.iterator()
activate ":ShowList"
":ShowList" -->> ":UserInterface": iterator
deactivate ":ShowList"
":UserInterface" -->> Clerk: shows
deactivate ":UserInterface"
@enduml