@startuml

actor Clerk

Clerk -> ":UserInterface" : List Customers
activate ":UserInterface"

":UserInterface" -> ":Theater" : getCustomerList()
activate ":Theater"
":Theater" -->> ":UserInterface": customerList
deactivate ":Theater"
":UserInterface" -> ":CustomerList": customerList.iterator()
activate ":CustomerList"
":CustomerList" -->> ":UserInterface": iterator
deactivate ":CustomerList"
":UserInterface" -->> Clerk: customers
deactivate ":UserInterface"
@enduml