@startuml

actor Clerk

Clerk -> ":UserInterface" : List Clients
activate ":UserInterface"

":UserInterface" -> ":Theater" : getClientList()
activate ":Theater"
":Theater" -->> ":UserInterface": clientList
deactivate ":Theater"
":UserInterface" -> ":ClientList": clientList.iterator()
activate ":ClientList"
":ClientList" -->> ":UserInterface": iterator
deactivate ":ClientList"
":UserInterface" -->> Clerk: clients
deactivate ":UserInterface"
@enduml