@startuml

actor Clerk

Clerk -> ":Interface" : List Clients
activate ":Interface"

":Interface" -> ":Theater" : getClientList()
activate ":Theater"
":Theater" -->> ":Interface": clientList
deactivate ":Theater"
":Interface" -> ":ClientList": clientList.iterator()
activate ":ClientList"
":ClientList" -->> ":Interface": iterator
deactivate ":ClientList"
":Interface" -->> Clerk: clients
deactivate ":Interface"
@enduml