@startuml

actor Clerk
participant ":UserInterface"
participant ":Theater"
participant ":ClientList"
participant ":CustomerList"
participant ":ShowList"
database Disk

Clerk -> ":UserInterface" : Load Data
activate ":UserInterface"

":UserInterface" -> ":Theater" : retrieveData()
activate ":Theater"

":Theater" -> ":ClientList": readObject()
activate ":ClientList"
":ClientList" -> Disk: readObject()
activate Disk
Disk -->> ":ClientList": status
":ClientList" -->> ":Theater": status
deactivate ":ClientList"

":Theater" -> ":CustomerList": readObject()
activate ":CustomerList"
":CustomerList" -> Disk: readObject()
Disk -->> ":CustomerList": status
":CustomerList" -->> ":Theater": status
deactivate ":CustomerList"

":Theater" -> ":ShowList": readObject()
activate ":ShowList"
":ShowList" -> Disk: readObject()
Disk -->> ":ShowList": status
":ShowList" -->> ":Theater": status
deactivate ":ShowList"

":Theater" -> Disk: readObject()
Disk -->> ":Theater": status

deactivate Disk

":Theater" -->> ":UserInterface": status
deactivate ":Theater"

":UserInterface" -->> Clerk: Status
deactivate ":UserInterface"
deactivate Clerk

@enduml