@startuml

actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Pay Client
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": clientId

activate ":Theater"
":UserInterface" -> ":Theater": getOwedToClient(clientId)
":Theater" -> ":Client": client = getClient(clientId)
activate ":Client"
":Theater" -> ":UserInterface" : client.getBalance()
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": payment
":UserInterface" -> ":Theater" : payClient(clientId, payment)
":Theater" -> ":Client" : adjustBalance(payment)
":Client" -->> ":Theater" : successful?
deactivate ":Client"
":Theater" -->> ":UserInterface" : successful?
deactivate ":Theater"
":UserInterface" -->> Clerk : successful?
deactivate ":UserInterface"
@enduml