@startuml
actor Clerk

Clerk -> ":UserInterface" : Print All Tickets (of given date)
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": date
activate ":UserInterface"

":UserInterface" -> ":Theater" : getTicketList(date)
activate ":Theater"
":Theater" -> ":TicketList" : getTickets(date)
activate ":TicketList"
":TicketList" -->> ":UserInterface": iterator
deactivate ":TicketList"
":UserInterface" -->> Clerk: tickets
deactivate ":UserInterface"
@enduml