@startuml

actor Clerk

Clerk -> ":UserInterface" : Remove a Customer
activate ":UserInterface"
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": id

":UserInterface" -> ":Theater" : getCustomerList()
activate ":Theater"
":Theater" -->> ":UserInterface": customerList
deactivate ":Theater"
":UserInterface" -> ":CustomerList": boolean = removeAccount(id)
activate ":CustomerList"
create "customer :Customer"
":CustomerList" -> "customer :Customer": customer = get(id)
destroy "customer :Customer"
":CustomerList" -->> ":UserInterface": successful?
deactivate ":CustomerList"
":UserInterface" -->> Clerk: successful?
deactivate ":UserInterface"
@enduml