@startuml
actor Clerk

activate ":UserInterface"
Clerk -> ":UserInterface" : Request to remove credit card
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": customerId

":UserInterface" -> ":Theater" : getCustomerList()
activate ":Theater"
":Theater" -->> ":UserInterface": CustomerList
deactivate ":Theater"
":UserInterface" -> ":CustomerList": customer = getAccount(customerId)
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": creditCardNumber
":UserInterface" -> ":customer: Customer" : boolean = customer.removeCreditCard(creditCardNumber)
activate ":customer: Customer"
":customer: Customer" -->> ":UserInterface" : successful?
deactivate ":CustomerList"
":UserInterface" -->> Clerk : successful?
deactivate ":UserInterface"
@enduml