@startuml

actor Clerk

Clerk -> ":UserInterface" : Remove a Client
activate ":UserInterface"
Clerk //- ":UserInterface": Data Request
Clerk -// ":UserInterface": id

":UserInterface" -> ":Theater" : getClientList()
activate ":Theater"
":Theater" -->> ":UserInterface": clientList
deactivate ":Theater"
":UserInterface" -> ":ClientList": boolean = removeAccount(id)
activate ":ClientList"
create "client :Client"
":ClientList" -> "client :Client": client
destroy "client :Client"
":ClientList" -->> ":UserInterface": successful?
deactivate ":ClientList"
":UserInterface" -->> Clerk: successful?
deactivate ":UserInterface"
@enduml