@startuml

actor Clerk
participant ":Interface"
participant ":Theater"
participant ":ClientList"
participant ":CustomerList"
participant ":ShowList"
database Disk

Clerk -> ":Interface" : Save Data
activate ":Interface"

":Interface" -> ":Theater" : storeData()
activate ":Theater"

":Theater" -> ":ClientList": writeObject()
activate ":ClientList"
":ClientList" -> Disk: writeObject()
activate Disk
Disk -->> ":ClientList": status
":ClientList" -->> ":Theater": status
deactivate ":ClientList"

":Theater" -> ":CustomerList": writeObject()
activate ":CustomerList"
":CustomerList" -> Disk: writeObject()
Disk -->> ":CustomerList": status
":CustomerList" -->> ":Theater": status
deactivate ":CustomerList"

":Theater" -> ":ShowList": writeObject()
activate ":ShowList"
":ShowList" -> Disk: writeObject()
Disk -->> ":ShowList": status
":ShowList" -->> ":Theater": status
deactivate ":ShowList"

":Theater" -> Disk: writeObject()
Disk -->> ":Theater": status

deactivate Disk

":Theater" -->> ":Interface": status
deactivate ":Theater"

":Interface" -->> Clerk: Status
deactivate ":Interface"
deactivate Clerk

@enduml