@startuml
skinparam classAttributeIconSize 0
hide empty members

class SingletonMap<K, E implements Identifiable<K>> {
    -INSTANCE: SingletonMap
    -singletonMap : Hashmap<Integer, E>
    -lastKey: Integer
    #SingletonMap()
    +getInstance() : SingletonMap
    +getNewKey(): Integer
    +addEntry(entry: E): boolean
    +removeEntry(keyId: Integer): boolean
    -readObject(ObjectInputStream)
    -writeObject(ObjectInputStream)
}

class AccountList<E extends Account> {
    -INSTANCE: AccountList
    +AccountList()
    +getInstance() : SingletonMap
    +getNewAccountId(): int
    +addAccount(account: E)
    +removeEntry(accountId: int): boolean
}

class ClientList {
    -INSTANCE: ClientList
    +ClientList()
    +getInstance() : ClientList
}

class CustomerList {
    -INSTANCE: ClientList
    +ClientList()
    +getInstance() : ClientList
}

class ShowList {
    -INSTANCE: ShowList
    +ShowList()
    +getInstance() : ShowList
    +addShow(Show)
    +validShowDate(Date) : boolean
    +checkShowDates(Account) : boolean

}

interface Identifiable<K> {
    +getId(): K
    +setId(K)
    +nextId(K): K
}

class IdentifiableInteger {
    -id: Integer
    +getId() : Integer
    +setId(Integer)
    +nextId(Integer) : Integer
     
}

class Account {
    -name: String
    -address: string
    -phoneNumber: long
    +Account(String, String, Long)
    +getName(): String
    +getAddress(): String
    +getPhoneNumber(): long
    +toString(): String
}

class Customer {
    -creditCardList: ArrayList<CreditCard>
    +Customer(String, String, long, CreditCard)
    +addCreditCard(CreditCard) : boolean
    +getCreditCard() : CreditCard
    +removeCreditCard(long) : boolean
    +removeCreditCards()
    +getCreditCardList() : ArrayList<CreditCard>
    +toString(): String
}

class Show {
    -name: String
    -endDate: Date
    -startDate: Date
    -showDateFormat: SimpleDateFormat
    +Show(Client, String, String, Date)
    +getClient() : Client
    +getName(): String
    +getEndDate(): Date
    +getStartDate(): Date
    +toString(): String
}

class Theater {
    -INSTANCE: Theater
    -clientList: ClientList
    -customerList: CustomerList
    -showList: ShowList
    +getInstance() : Theater
    +getClientList(): ClientList
    +getCustomerList(): CustomerList
    +getShowList(): ShowList
    +storeData() : boolean
    +retrieveData(): Theater
    +hasData(): boolean
    -readObject(ObjectInputStream)
    -writeObject(ObjectInputStream)
}

Theater <-- "ClientList"
Theater <-- "CustomerList"
Theater <-- "ShowList"

"Identifiable" <|-- "Identifiable<Integer>" : "«bind» K::Integer"
"Identifiable<Integer>" <|-- "IdentifiableInteger"
SingletonMap <|-- "SingletonMap<Account>" : "«bind» E::Account"
SingletonMap <|-- "SingletonMap<Show>" : "«bind» E::Show"
"SingletonMap<Account>" <|-- AccountList
"SingletonMap<Show>" <|-- ShowList
AccountList <|-- "AccountList<Client>" : "«bind» E::Client"
AccountList <|-- "AccountList<Customer>" : "«bind» E::Customer"
"AccountList<Client>" <|-- ClientList
"AccountList<Customer>" <|-- CustomerList

IdentifiableInteger <|-- Account
IdentifiableInteger <|-- Show

Account <|-- Client
Account <|-- Customer

AccountList *-- Account
ClientList *-- Client
CustomerList *-- Customer
ShowList *-- Show
@enduml